name: YouTube Auto Upload

on:
  schedule:
    - cron: '0 4 * * *'  # Every day at 4 AM
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run automation pipeline
      run: |
        mkdir -p output
        python generate_script.py
        python generate_voiceover.py
        python download_images.py
        python create_video.py
        python create_thumbnail.py

    - name: Upload video artifact
      uses: actions/upload-artifact@v4
      with:
        name: final_video
        path: output/final_video.mp4

    - name: Upload thumbnail artifact
      uses: actions/upload-artifact@v4
      with:
        name: thumbnail
        path: output/thumbnail.png
